# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmcat_chart.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_childChart(object):
    def setupUi(self, childChart):
        childChart.setObjectName("childChart")
        childChart.resize(1770, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/CmCat_Res/5G.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        childChart.setWindowIcon(icon)
        self.label_chart = QtWidgets.QLabel(childChart)
        self.label_chart.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.label_chart.setStyleSheet("font: 9pt \"Impact\";")
        self.label_chart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_chart.setObjectName("label_chart")
        self.widget_chart = QtWidgets.QWidget(childChart)
        self.widget_chart.setGeometry(QtCore.QRect(10, 40, 1751, 951))
        self.widget_chart.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_chart.setObjectName("widget_chart")

        self.retranslateUi(childChart)
        QtCore.QMetaObject.connectSlotsByName(childChart)

    def retranslateUi(self, childChart):
        _translate = QtCore.QCoreApplication.translate
        childChart.setWindowTitle(_translate("childChart", "CmChart"))
        self.label_chart.setText(_translate("childChart", "Chart"))
import core_res_rc
